# Gemfile
source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'activerecord'
gem 'sqlite3'
gem 'ruby-trello'
gem 'openai'
gem 'http'
gem 'anthropic'
gem 'rails'
gem 'nokogiri'
gem 'dotenv'
gem 'gemini-ai', '~> 4.2'
gem 'rufus-scheduler'
gem 'byebug'
